

from curio.errors import CurioError


class TaskNotFoundExc(CurioError):
    pass



def main():
    return


if __name__ == "__main__":
    main()
